version: '3'

services:
  web:
    build:
      context: .
      target: dev 
    tty: true
    volumes: 
      - ./src:/app/src
      - ./public:/app/public
      - ./database_files:/app/database_files
    ports:
      - "80:80"


